config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'books' => 'books#index'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as:'book'
  get 'books/:id/edit' => 'books#edit', as:'edit_book'
  patch 'books/:id' => 'books#update', as:'update_book'
  delete 'books/:id' => 'books#destroy', as:'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @new_book = Book.new
  end

  def new
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @new_book = Book.new(book_params)
     if @new_book.save
       flash[:notice] = "Book was successfully created."
       redirect_to book_path(@new_book)
     else
       @books = Book.all
       render "index"
     end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:alret] = "Book was successfully updated."
     redirect_to book_path(@book.id)
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private
  def book_params
    params.require(:book) .permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/new_controller.rb
class NewController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>>
   <%= @book.errors.count %>error prohibited this book from being saved:
   <ul>
    <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
   </ul>
  <% end %>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

 <div class = "field">
  <lavel for = "book_title">Title</lavel><br>
  <%= f.text_field :title %>
 </div>

 <div class = "field">
  <lavel for = "book_body">Body</lavel><br>
  <%= f.text_area :body %>
 </div>

 <div class = "actions">
  <%= f.submit 'Update Book' %>
 </div>

 <%= link_to "Show", book_path(@book.id) %>
 |
 <a href = "/books">Back</a>

<% end %>

app/views/books/index.html.erb
<html>

 <head>
  <title>WebCampBackendNew</title>
  <link rel="stylesheet" href="application.css">
 </head>

 <body>
  <h1>Books</h1>

  <table>

   <thead>
    <tr>
     <th>Title</th>
     <th>Body</th>
     <th colspan="3"></th>
    </tr>
   </thead>

   <tbody>
    <% @books.each do |book| %>
     <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show", book_path(book.id) %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
     </tr>
    <% end %>
   </tbody>

  </table>

  <h2>New book</h2>

  <% if @new_book.errors.any? %>>
   <%= @new_book.errors.count %>error prohibited this book from being saved:
   <ul>
    <% @new_book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
   </ul>
  <% end %>

  <%= form_with model: @new_book, url:'/books', local:true do |f| %>

  <div class = "field">
   <lavel for = "book_title">Title</lavel><br>
   <%= f.text_field :title %>
  </div>

  <div class = "field">
   <lavel for = "book_body">Body</lavel><br>
   <%= f.text_area :body %>
  </div>

  <div class = "actions">
   <%= f.submit 'Create Book' %>
  </div>

  <% end %>

 </body>
</html>

app/views/books/show.html.erb
<p><strong>Title:</strong>
<%= @book.title %></p>

<p><strong>Body:</strong>
<%= @book.body %></p>
 
<%= link_to "Edit", edit_book_path(@book.id) %>
| 
<a href = "/books">Back</a>

app/views/homes/top.html.erb
<html>
 <head>
  <title>WebCampBackendNew</title>
  <link rel="stylesheet" href="application.css">
 </head>

  <body>
    <h1>
      ようこそ
      <strong>Bookers</strong>
      へ！
    </h1>

    <p>
      <strong>Bookers</strong>
      では、さまざまな書籍に関するあなたの意見や
    </p>

    <p>
      印象を共有し交換することができます
    </p>

    <p>
      <a href = "/books">start</a>
    </p>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = "text-success">
      <%= flash[:notice] %>
    </div>

    <div class = "text-danger">
      <%= flash[:alret] %>
    </div>
    
    <%= yield %>
  </body>
</html>